config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :cocktails  do
    collection do
      get 'search', 'search_by_ingredient', 'search_by_name'
    end
  end
  resources :favorites, only: [:create, :destroy, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :favorites
  has_many :users, through: :favorites
end

app/models/cocktail_service.rb
class CocktailService
  def self.get_random_cocktail
    cocktails = HTTParty.get("http://www.thecocktaildb.com/api/json/v1/1/random.php", :headers =>{'Content-Type' => 'application/json'} )["drinks"]

    cocktails.first
  end

 def self.get_cocktail_by_id(search_term)
     cocktail = HTTParty.get("https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=#{search_term}", :headers =>{'Content-Type' => 'application/json'} )["drinks"]

     cocktail.first
  end 

  def self.get_cocktail_by_name(search_term)
    cocktails = HTTParty.get("http://www.thecocktaildb.com/api/json/v1/1/search.php?s=#{search_term}", :headers =>{'Content-Type' => 'application/json'} )["drinks"]

    cocktails
  end

  def self.get_cocktail_by_ingredient(search_term)
    cocktails = HTTParty.get("http://www.thecocktaildb.com/api/json/v1/1/filter.php?i=#{search_term}", :headers =>{'Content-Type' => 'application/json'} )["drinks"]

    cocktails
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user, class_name: "User"
  belongs_to :cocktail, class_name: "Cocktail"
  validates :user_id, presence: true
  validates :cocktail_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cocktails, dependent: :destroy

  has_many :favorites, dependent: :destroy
                      
  has_many :favorited_cocktails, :through => :favorites, :source => :cocktail

  def self.created_today
    where('created_at >= ?', Time.current.beginning_of_day)
  end

 
  def add_favorite(cocktail)

    self.favorites.create(user_id: self.id, cocktail_id: cocktail.id, api_id: cocktail.api_id)
  end


  def favorited_api_cocktail?(cocktail_api_id)
    favorited_cocktails.find_by(api_id: cocktail_api_id).present?
  end

  def favorited?(cocktail_id)
    favorited_cocktails.find_by(id: cocktail_id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def search
    @cocktail = CocktailService.get_random_cocktail
  end

  def new
    render 'new'
  end

  def create
    cocktail = Cocktail.create!(
      name: params["name"], 
      image_url: params["image_url"], 
      measure1: params["measure1"], 
      ingredient1: params["ingredient1"], 
      measure2: params["measure2"], 
      ingredient2: params["ingredient2"],
      measure3: params["measure3"], 
      ingredient3: params["ingredient3"],
      instructions: params["instructions"],
      user_id: current_user.id
    )

    redirect_to cocktail_path(cocktail.id)
  end

  def search_by_name
    query = params[:name].downcase

    if query.present? 
      @user_sumbitted_cocktails = Cocktail.where("lower(name) LIKE ?", "%#{query}%").where.not(user_id:nil)
      @api_cocktails = CocktailService.get_cocktail_by_name(query)
      
      render 'show_search_results'
    else 
      redirect_to '/cocktails/search'
    end
  end

  def search_by_ingredient
    query = params[:ingredient]

    if query.present? 
      @user_sumbitted_cocktails = Cocktail.where("lower(ingredient1) LIKE :search OR lower(ingredient2) LIKE :search OR lower(ingredient3) LIKE :search",  :search => "%#{query}%").where.not(user_id:nil)
      @api_cocktails = CocktailService.get_cocktail_by_ingredient(query)
      
      render 'show_search_results'
    else
      redirect_to '/cocktails/search'
    end
  end

  def show
    @is_api_cocktail = params[:api_cocktail].present?

    if @is_api_cocktail
      @cocktail = CocktailService.get_cocktail_by_id(params[:id])
    else
      @cocktail = Cocktail.find(params[:id])
    end
    
    render 'show'
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    if current_user
      @favorited_cocktails = current_user.favorited_cocktails 
    else 
      render "sessions/new"
    end
  end

  def create
    cocktail = api_cocktail? ? find_or_create_api_cocktail : find_user_submitted_cocktail
      
    current_user.add_favorite(cocktail)
    
    respond_to do |format|
      format.js
      format.html
    end
  end

  def destroy
    favorite = Favorite.find(params[:id])
    favorite.delete

    respond_to do |format|
      format.js
      format.html
    end
  end

  private

  def api_cocktail?
    params[:api_id].present?
  end

  def find_or_create_api_cocktail
    Cocktail.find_or_create_by(api_id: params[:api_id], name: params[:name], image_url: params[:image_url] )
  end

  def find_user_submitted_cocktail
    Cocktail.find(params[:cocktail_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @favorited_cocktails = current_user.favorited_cocktails unless !current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   # Returns true if the user is logged in, false otherwise.
  def logged_in?
    current_user.present?
  end
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cocktails/_favorite.html.erb
<%= form_with(model: current_user.favorites.build, local: true) do |f| %>
  <div><%= hidden_field_tag :user_id, current_user.id %></div>
  <div><%= hidden_field_tag :api_id, cocktail["idDrink"] %></div>
  <div><%= hidden_field_tag :image_url, cocktail["strDrinkThumb"] %></div>
  <div><%= hidden_field_tag :name, cocktail["strDrink"] %></div>
  <%= f.submit "Favorite", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/new.html.erb
<main>
  <h1 class="text-center my-5"> Submit a Recipe </h1>

  <form class="col-lg-6 offset-lg-3" action="/cocktails" method="post">
    <div class="form-group">
      <label for="inputName">Cocktail Name</label>
      <input type="text" class="form-control" id="inputName" name="name" placeholder="Classic Margarita">
    </div>
    <div class="form-group">
      <label for="inputImgUrl">Image URL</label>
      <input type="text" class="form-control" id="inputImgUrl" name="image_url" placeholder= "https://www.example.jpg">
    </div>
    <div class="form-row row">
      <div class="form-group col-6">
        <label for="inputMeasure1">Measurement</label>
        <input type="text" class="form-control mt-1" id="inputMeasure1" name="measure1" placeholder="1 1/2 oz">
      </div>
      <div class="form-group col-6">
        <label for="inputIngredient1">Ingredient</label>
        <input type="text" class="form-control mt-1" id="inputIngredient1" name="ingredient1" placeholder="silver tequila">
      </div>
    </div>


    <div class="form-row row">
      <div class="form-group col-6">
        <input type="text" class="form-control mt-1" id="inputMeasure2" name="measure2"placeholder="1 oz">    
      </div>
      <div class="form-group col-6">
        <input type="text" class="form-control mt-1" id="inputIngredient2" name="ingredient2" placeholder="orange liqueur">
      </div>
    </div>


    <div class="form-row row">
      <div class="form-group col-6">
        <input type="text" class="form-control mt-1" id="inputMeasure3" name="measure3" placeholder="3/4 oz">    
      </div>
      <div class="form-group col-6">
        <input type="text" class="form-control mt-1" id="inputIngredient3" name="ingredient3" placeholder="lime juice">
      </div>
    </div>

    <div class="form-group">
      <label for="instructions">Instructions</label>
      <textarea class="form-control" id="instructions" rows="3" name="instructions" placeholder="Mix and serve!"></textarea>
    </div>

    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
  </form>
</main>

app/views/cocktails/search.html.erb
<main>
  <section class = "py-5 text-center container">
    <div class ="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class = fw-light> Find your next drink</h1>
        <p class="mt-5"> 
          <a class = "btn btn-primary my-2" id="search_by_name_btn">Search by name</a>
          <a class = "btn btn-outline-primary my-2" id="search_by_ingredient_btn">Search by ingredient</a>
        </p>
        <form id="search_form" action="/cocktails/search_by_name">
          <div class="form-group">
            <input type="text" class="form-control" id="search_input" name = "name" placeholder="Margarita">
          </div>
          <button type="submit" id="submit-btn" class="btn btn-primary mt-2">Submit</button>
        </form>
      </div>
    </div>
  </section>
</main>

app/views/cocktails/show.html.erb
<h1 class="cocktail-name text-center"><%=@cocktail["strDrink"] || @cocktail.name%></h1>
<hr class="my-4">

<div class="row">
  <div class="col-sm-6 text-center" >
    <img src="<%= @cocktail["strDrinkThumb"] || @cocktail.image_url %>" alt="cocktail image" width= "300" height = "300" >

    <% if @is_api_cocktail %>
      <% if current_user.present? %>
        <div id="favorite_form" class="mt-3">
          <% if current_user.favorited_api_cocktail?(@cocktail["idDrink"]) %>
            <%= render 'shared/unfavorite_api' , api_id: @cocktail["idDrink"], cocktail: @cocktail %>
          <% else %>
            <%= render 'shared/favorite_api' , api_id: @cocktail["idDrink"], cocktail: @cocktail %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <% if current_user.present? %>
        <div id="favorite_form" class="mt-3">
          <% if current_user.favorited?(@cocktail.id) %>
            <%= render 'shared/unfavorite_user_submitted' , cocktail: @cocktail %>
          <% else %>
            <%= render 'shared/favorite_user_submitted' , cocktail: @cocktail %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="col-sm-6 recipe-text">
    <% if @is_api_cocktail %>
      <%= render 'shared/api_cocktail_recipe' %>
    <% else %>
      <%= render 'shared/user_submitted_cocktail_recipe' %>
    <% end %>
  </div>
</div>   

 
    

app/views/cocktails/show_search_results.html.erb
</main>
  <h1 class="text-center mb-5 pt-3"> Search Results </h1>

  <% if @api_cocktails.present? %>
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-3">
        <% @api_cocktails.each do |api_cocktail| %>
          <div class="col">
            <div class="card shadow-sm h-100">
              <img class="bd-placeholder-img card-img-top" width="300px" height="300px" src='<%= api_cocktail["strDrinkThumb"] %>' aria-label="Placeholder: Thumbnail">
              <div class="card-body h-100">
                <p class="card-text">
                  <%= api_cocktail["strDrink"] %>
                </p>
                <div class="d-flex justify-content-between    align-items-center">
                  <div class="btn-group">
                    <input type="button" class="btn btn-sm btn-outline-secondary"
                      onclick="location.href = '<%= cocktail_path(api_cocktail["idDrink"], api_cocktail: true) %>';"
                    value="View" />
                  </div>
                  <% if current_user.present? %>
                    <div id="favorite_form">
                      <% if current_user.favorited_api_cocktail?(api_cocktail["idDrink"]) %>
                        <%= render 'shared/unfavorite_api' , api_id: api_cocktail["idDrink"], cocktail: api_cocktail %>
                      <% else %>
                        <%= render 'shared/favorite_api' , api_id: api_cocktail["idDrink"], cocktail: api_cocktail %>
                      <% end %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @user_sumbitted_cocktails.present? %>
    <div class="row">
      <h2 class="mt-5 text-center mb-5"> User Submitted </h2>
    </div>
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-3">
        <% @user_sumbitted_cocktails.each do |user_submitted_cocktail| %>
          <div class="col">
            <div class="card shadow-sm h-100">
              <img class="bd-placeholder-img card-img-top" width="300px" height="300px"
                src="<%= user_submitted_cocktail.image_url %>" aria-label="Placeholder: Thumbnail">
              <div class="card-body">
                <p class="card-text">
                  <%= user_submitted_cocktail.name %>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <input type="button" class="btn btn-sm btn-outline-secondary"
                      onclick="location.href = '<%= cocktail_path(user_submitted_cocktail.id) %>';"
                      value="View" />
                  </div>
                 <% if current_user.present? %>
                  <div id="favorite_form">
                    <% if current_user.favorited?(user_submitted_cocktail.id) %>
                      <%= render 'shared/unfavorite_user_submitted' , cocktail: user_submitted_cocktail %>
                    <% else %>
                      <%= render 'shared/favorite_user_submitted' , cocktail: user_submitted_cocktail %>
                    <% end %>
                  </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</main>

app/views/favorites/index.html.erb
</main>
  <div class ="album py-5 bg-light">
    <h1 class="text-center mb-5"> Your Favorites </h1>
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-3">
        <%  @favorited_cocktails.each do |favorited_cocktail| %>
          <div class="col">
            <div class="card shadow-sm">
              <img class ="bd-placeholder-img card-img-top" width="300px" height ="300px" src="<%= favorited_cocktail.image_url %>" aria-label="Placeholder: Thumbnail">
              <div class="card-body">
                <p class="card-text">
                  <%= favorited_cocktail.name %>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <% if favorited_cocktail.api_id.present? %>
                      <input type="button" class="btn btn-sm btn-outline-secondary" onclick= "location.href = '<%= cocktail_path(favorited_cocktail.api_id, api_cocktail: true ) %>';" value="View" />
                    <% else %>
                      <input type="button" class="btn btn-sm btn-outline-secondary" onclick= "location.href = '<%= cocktail_path(favorited_cocktail.id) %>';" value="View" />
                    <% end %>
                  </div>
                  <div id="favorite_form">
                    <% if current_user.favorited?(favorited_cocktail.id) %>
                      <%= render 'shared/unfavorite_api', api_id: favorited_cocktail.api_id %>
                    <% else %>
                      <%= render 'shared/favorite_api', cocktail: favorited_cocktail %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/home/index.html.erb
  <div class="jumbotron">
    <div class="container">
      <% name = current_user.present? ? 'Friend' : 'Stranger' %>
      <h1 class="display-md-4 display-5 pt-4"> Hello, <%= name %>! </h1>
      <p class="lead"> Find your next drink. </p>
      <hr class="my-4">
      <p> Search from hundreds of cocktails by name or ingredient and save your favorites.</P>
      <p>
        <a class="btn btn-primary btn-lg" href="/cocktails/search" role="button"> Start Searching</a>
      </p>    
    </div>
  </div>
<main role="main">
  <% if current_user.present? %>
    <h1 class="text-center mb-5 mt-3"> Your Favorites </h1>
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-3">
        <%  @favorited_cocktails.each do |favorited_cocktail| %>
          <div class="col">
            <div class="card shadow-sm">
              <img class ="bd-placeholder-img card-img-top" width="300px" height ="300px" src="<%= favorited_cocktail.image_url %>" aria-label="Placeholder: Thumbnail">
              <div class="card-body">
                <p class="card-text">
                  <%= favorited_cocktail.name %>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <% if favorited_cocktail.api_id.present? %>
                      <input type="button" class="btn btn-sm btn-outline-secondary" onclick= "location.href = '<%= cocktail_path(favorited_cocktail.api_id, api_cocktail: true) %>';" value="View" />
                    <% else %>
                      <input type="button" class="btn btn-sm btn-outline-secondary" onclick= "location.href = '<%= cocktail_path(favorited_cocktail.id) %>';" value="View" />
                    <% end %>
                  </div>
                  <%= render 'shared/unfavorite_api', api_id: favorited_cocktail.api_id %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <% else %>
      <div class="container">
        <div class="row">
          <div class="col-md-4 mt-2">
            <h2>Hundreds of Recipes</h2>
            <p> Hundreds of contemporay and classic cocktails at your finger tips. Search by cocktail name or ingredient!</p>
          </div>
          <div class="col-md-4">
            <h2>Add to Favorites</h2>
            <p> Create an account to save your favorite cocktail recipes for later!</p>
          </div>
          <div class="col-md-4">
            <h2>Share Your Own</h2>
            <p> Submit your own unqiue recipes to share with the community </p>
          </div>
        </div>
      </div>
  <% end %>  
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <title>CocktailApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Lobster&family=Poppins&display=swap');
    </style>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
   
    <%= yield %>

  </body>
</html>

app/views/shared/_api_cocktail_recipe.html.erb
<div class = "col-10 offset-1 col-md-10">
  <p>
    <%= @cocktail["strMeasure1"] %>
    <%= @cocktail["strIngredient1"] %>
  </p>

  <p>
    <%= @cocktail["strMeasure2"] %>
    <%= @cocktail["strIngredient2"] %>
  </p>

  <p>
    <%= @cocktail["strMeasure3"] %>
    <%= @cocktail["strIngredient3"] %>
  </p>

  <p>
    <%= @cocktail["strMeasure4"] %>
    <%= @cocktail["strIngredient4"] %>
  </p>

  <p>
    <%= @cocktail["strMeasure5"] %>
    <%= @cocktail["strIngredient5"] %>
  </p>

  <p>
    <%= @cocktail["strMeasure6"] %>
    <%= @cocktail["strIngredient6"] %>
  </p>
    
  <p>
    <%= @cocktail["strMeasure7"] %>
    <%= @cocktail["strIngredient7"] %>
  </p>
    
  <p>
    <%= @cocktail["strMeasure8"] %>
    <%= @cocktail["strIngredient8"] %>
  </p>
    
  <p>
    <%= @cocktail["strMeasure9"] %>
    <%= @cocktail["strIngredient9"] %>
  </p>
    
  <p>
    <%= @cocktail["strMeasure10"] %>
    <%= @cocktail["strIngredient10"] %>
  </p>
    
  <p>
    <%= @cocktail["strMeasure11"] %>
    <%= @cocktail["strIngredient11"] %>
  </p>
    
  <p>
    <%= @cocktail["strMeasure12"] %>
    <%= @cocktail["strIngredient12"] %>
  </p>
    
  <p>
    <%= @cocktail["strMeasure13"] %>  
    <%= @cocktail["strIngredient13"] %>
  </p>

  <p>  
    <%= @cocktail["strMeasure14"] %>
    <%= @cocktail["strIngredient14"] %>
  </p>

  <p>
    <%= @cocktail["strMeasure15"] %>
    <%= @cocktail["strIngredient15"] %>
  </p>

  <p>
    <%= @cocktail["strInstructions"] %>
  </p>
</div>

app/views/shared/_favorite.html.erb
<%= form_with(model: current_user.favorites.build, local: false) do |f| %>
  <div><%= hidden_field_tag :user_id, current_user.id %></div>
  <div><%= hidden_field_tag :api_id, api_id %></div>
  <div><%= hidden_field_tag :image_url, cocktail["strDrinkThumb"] %></div>
  <div><%= hidden_field_tag :name, cocktail["strDrink"] %></div>
  <%= f.submit "Favorite", class: "favorite-btn btn btn-primary" %>
<% end %>

app/views/shared/_favorite_api.html.erb
<%= form_with(model: current_user.favorites.build, local: false) do |f| %>
  <div><%= hidden_field_tag :user_id, current_user.id %></div>
  <div><%= hidden_field_tag :api_id, api_id %></div>
  <div><%= hidden_field_tag :image_url, cocktail["strDrinkThumb"] %></div>
  <div><%= hidden_field_tag :name, cocktail["strDrink"] %></div>
  <%= f.submit "Favorite", class: "favorite-btn btn btn-primary" %>
<% end %>

app/views/shared/_favorite_user_submitted.html.erb
<%= form_with(model: current_user.favorites.build, local: false) do |f| %>
  <div><%= hidden_field_tag :cocktail_id, cocktail.id %></div>
  <%= f.submit "Favorite", class: " favorite-btn btn btn-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <a class="navbar-brand mx-3" href="/">Cocktail Findr</a>
  <button class="navbar-toggler mx-3" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ms-2 ms-lg-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Submit a Recipe', new_cocktail_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Favorite Cocktails', favorites_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
         <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_unfavorite.html.erb
<%= form_with(model: current_user.favorites.find_by(api_id: api_id), html: {method: :delete}, local: false) do |f| %>
  <%= f.submit "Unfavorite", class: "unfavorite-btn btn btn-outline-primary" %>
<% end %>

app/views/shared/_unfavorite_api.html.erb
<%= form_with(model: current_user.favorites.find_by(api_id: api_id), html: {method: :delete}, local: false) do |f| %>
  <%= f.submit "Unfavorite", class: "unfavorite-btn btn btn-outline-primary" %>
<% end %>

app/views/shared/_unfavorite_user_submitted.html.erb
<%= form_with(model: current_user.favorites.find_by(cocktail_id: cocktail.id), html: {method: :delete}, local: false) do |f| %>
  <%= f.submit "Unfavorite", class: "unfavorite-btn btn btn-outline-primary" %>
<% end %>

app/views/shared/_user_submitted_cocktail_recipe.html.erb
<div class = "col-10 offset-1 col-md-10">
  <p>
    <%= @cocktail.measure1 %>
    <%= @cocktail.ingredient1 %>
  </p>

  <p>
    <%= @cocktail.measure2 %>
    <%= @cocktail.ingredient2 %>
  </p>

  <p>
    <%= @cocktail.measure3 %>
    <%= @cocktail.ingredient3 %>
  </p>

  <p>
    <%= @cocktail.measure4 %>
    <%= @cocktail.ingredient4 %>
  </p>

  <p>
    <%= @cocktail.measure5 %>
    <%= @cocktail.ingredient5 %>
  </p>

  <p>
    <%= @cocktail.measure6 %>
    <%= @cocktail.ingredient6 %>
  </p>
    
  <p>
    <%= @cocktail.measure7 %>
    <%= @cocktail.ingredient7 %>
  </p>
    
  <p>
    <%= @cocktail.measure8 %>
    <%= @cocktail.ingredient8 %>
  </p>
    
  <p>
    <%= @cocktail.measure9 %>
    <%= @cocktail.ingredient9 %>
  </p>
    
  <p>
    <%= @cocktail.measure10 %>
    <%= @cocktail.ingredient10 %>
  </p>
    
  <p>
    <%= @cocktail.measure11 %>
    <%= @cocktail.ingredient11 %>
  </p>
    
  <p>
    <%= @cocktail.measure12 %>
    <%= @cocktail.ingredient12 %>
  </p>
    
  <p>
    <%= @cocktail.measure13 %>  
    <%= @cocktail.ingredient13 %>
  </p>

  <p>  
    <%= @cocktail.measure14 %>
    <%= @cocktail.ingredient14 %>
  </p>

  <p>
    <%= @cocktail.measure15 %>
    <%= @cocktail.ingredient15 %>
  </p>

  <p>
    <%= @cocktail.instructions %>
  </p>
</div> 